### ISSUE TITLE
Remove dependency on Immutable.js?

### ISSUE THREAD

**Issue by kutyel** [kutyel/linq.ts#1]
I would like the opinion of the community regarding whether I should remove the dependency upon Immutable.js or not. As I return a new instance of my class every time in most methods, this makes the library already "immutable" by definition. Moreover, this would allow me to make my own methods implementation, maybe using approaches similar to the ones in **lodash** to make it as fastest as possible.

**Comment by keropodium** [comment]
![YES](http://i.giphy.com/3o7abB06u9bNzA8lu8.gif)

**Comment by kutyel** [comment]
Ok, *alea jacta est*. Thanks for the feedback!
