### ISSUE TITLE
why not extend the plain JavaScript 'Array' type ?

### ISSUE THREAD

**Issue by JaggerJo** [kutyel/linq.ts#100]
Is there a reason why these methods are not availiable on any plain JavaScript Array ?
We could simply add them to the Prototype, right ?

For Example
```javascript
Array.prototype.firstOrDefault = (...) => x
```
and
```typescript
interface Array<T> {
    firstOrDefault(...) : T;
}
```

**Comment by kutyel** [comment]
Actually its a very interesting question! Thanks for asking! The answer is mainly that extending prototypes in JavaScript its a **very bad practice**. It's only allowed to add missing standard features (pollyfils) that are not yet implemented. Generally its a much better pattern to wrap an abstraction and use that instead, which is exactly what the `List` component is, a wrapper of an internal JS array 😉

**Comment by kutyel** [comment]
BTW: you can support the library by sharing it and giving it a ⭐️  in GitHub! 😉
