### ISSUE TITLE
Reccommend: Add method toMap

### ISSUE THREAD

**Issue by twoeo** [kutyel/linq.ts#11]
Always need convert an array to  map ...

**Comment by kutyel** [comment]
Could you please explain in more detail what this `ToMap()` function would do?

In the LINQ specification there are only these converting methods:
- [ToArray()](https://msdn.microsoft.com/en-us/library/bb298736.aspx)
- [ToDictionary()](https://msdn.microsoft.com/en-us/library/bb549277.aspx)
- [ToList()](https://msdn.microsoft.com/en-us/library/bb342261.aspx)
- [ToLookup()](https://msdn.microsoft.com/en-us/library/bb549346(v=vs.110).aspx)

**Comment by kutyel** [comment]
Closed by the lack of response. If the contributor answers and the Issue is real, will reopen it.

**Comment by twoeo** [comment]
ToDictionary works!  Thanks!~
