### ISSUE TITLE
Provide types for linq.ts

### ISSUE THREAD

**Issue by DMW007** [kutyel/linq.ts#114]
It seems that linq.ts doesn't provide any types, since no `@types/linq.ts` package exist and after installing the main package, I got no intellisense in VS Code using [TypeScript Importer](https://marketplace.visualstudio.com/items?itemName=pmneo.tsimporter). This forces me to manually type imports like `import { List } from 'linq.ts';` on every time I want to use linq.ts, which is very annoying and not the level of C#. 

So please provide typings for a efficient usage of linq.ts in TypeScript.

**Comment by kutyel** [comment]
Which package are you using `linqts` or `linq.ts`? The first one should have type declarations without having to import anything from the `@types` namespace, can you try it?

**Comment by kutyel** [comment]
I've checked the TypeScript [documentation](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) regarding publishing and I am doing exactly what is required from a library author, the type definitions are shipped in the `/dist/index.d.ts` folder. It is not my concern that the plugin you use for you editor does not detect that type declaration files. Also, you can add the types yourself by publishing to the @types organization.
