### ISSUE TITLE
'this' is undefined inside const declaration

### ISSUE THREAD

**Issue by lebdimaa** [kutyel/linq.ts#115]
The compiled code transform 'this' to 'void 0' and I get an error " Cannot read property '_equal' of undefined".

https://github.com/kutyel/linq.ts/blob/49bbebd6025e1d4a632786f6e987bb5b53705555/index.ts#L11

**Comment by kutyel** [comment]
wow huge mistake, I'll fix it ASAP, thx for reporting it! 👍
