### ISSUE TITLE
UglifyJS error during gulp bundle --ship

### ISSUE THREAD

**Issue by haifoo** [kutyel/linq.ts#118]
One of our projects use the library for querying against sharepoint lists.
The project runs ok on dev, but generates a build error once we try to build for production.

steps to reproduce:
1. create new ms spfx project using yoeman generator (webpart, o365 only)
2. npm install linqts --save
3. use library in code
```ts
import { List } from 'linqts';
export default class SampleFabric extends React.Component<ISampleFabricProps, {}> {
  public render(): React.ReactElement<ISampleFabricProps> {
    
    let dataList = new List(["a", "b"]);
    ...
}
```
4. gulp bundle --ship

returns this error:
```sh
Error - [webpack] 'dist':
sample-fabric-web-part.js from UglifyJs
Unexpected token: operator (>) [sample-fabric-web-part.js:738,10]
```

reverting to v1.10.0 (`npm install --save-exact linqts@1.10.0`) will allow the build to complete.

**Comment by marlon-tucker** [comment]
I am also encountering this issue.

It seems a newer release is shipping ES6 code, with lambda functions. At the moment we are not using Babel to transpile down to ES5. 

As this project does not mention the requirement for Babel to provide this functionality. Would you consider altering the publishing method to output ES5 compliant code?

**Comment by kutyel** [comment]
Tomorrow I'll release a new version reestablishing the dist version to es5, should fix this issue and @huserben's one as well! 😄

**Comment by huserben** [comment]
ok, thanks for the info. I'll consider updating when I release the next version of my task.

Thanks again for your support and quick responses.

**Comment by haifoo** [comment]
thanks!
