### ISSUE TITLE
OrderBy sorts in ASCII style

### ISSUE THREAD

**Issue by mstrzoda** [kutyel/linq.ts#122]
OrderBy sorts first big letters, then small and then special characters like language specific letters. List like this: "Ägypten", "Griechenland", "Deutschland" will be sorted in that way:
"Deutschland", "Griechenland", "Ägypten".  "Ägypten" should be first in that example.

**Comment by kutyel** [comment]
Is this an issue? I mean, JavaScript can only order strings according to ASCII positions, if not you would have to provide your custom sorting according to your specific needs/language, how would you improve this? 😄

**Comment by mstrzoda** [comment]
i think we could use at some point this function:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare,

or we should allow devs to inject his own comparer like in original OrderBy:
https://msdn.microsoft.com/pl-pl/library/bb549422(v=vs.110).aspx

**Comment by kutyel** [comment]
Great feedback! I think the most flexible solution is to implement the optional comparer parameter, and it is also an easy fix! 😉 Feel free to land a PR if you feel like it, if not I will fix it this week!

**Comment by mstrzoda** [comment]
If you have some free time please do that, i have huuuuuuuge task to do by the end of the month (i don't know if i will have time for sleep :/)

**Comment by mstrzoda** [comment]
great, big thx!

**Comment by kutyel** [comment]
Hope you like the new test 😜 https://github.com/kutyel/linq.ts/blob/master/test/list.ts#L479-L484

**Comment by mstrzoda** [comment]
schööööön!
