### ISSUE TITLE
List from API

### ISSUE THREAD

**Issue by lilling** [kutyel/linq.ts#13]
How can I get `List<T>` instead of `Array<T>` from API?

In development I have autocomplete as if it is a `List<T>` as it should but at run time it becomes an `Array<T>` and I fall on LINQ functions...

Help will be appreciated.

**Comment by kutyel** [comment]
I don't really understand what you mean. In the LINQ specification there are only this converting methods:
- [ToArray()](https://msdn.microsoft.com/en-us/library/bb298736.aspx)
- [ToDictionary()](https://msdn.microsoft.com/en-us/library/bb549277.aspx)
- [ToList()](https://msdn.microsoft.com/en-us/library/bb342261.aspx)
- [ToLookup()](https://msdn.microsoft.com/en-us/library/bb549346(v=vs.110).aspx)
If you provide none of this methods, the `List<T>` remains as it is:
```typescript
const test = new List<number>();
console.log(test.ToArray()); // > []
console.log(test.ToList()); // > List
console.log(test); // > List
```
Can you provide some code that shows what you are trying to accomplish?

**Comment by lilling** [comment]
I have an incident class
```javascript
class Incident implements IIncident {  
    constructor(public incidentId : number, 
                public name : string,
                public tags : string[],
                public _status : IncidentStatus, 
                public host : string,
                public severity : number,
                public lastModified : Date,
                public selectedUser : User,
                public comments : string[],
                public agents : List<Agent>)()
}
```
iI get a Incident[] from the api.

Is there a way to get List<Incdient> directly instead of loop over the arry and initilize every object?

**Comment by kutyel** [comment]
Easy. So you basically receive an array and want a `List<T>` out of it. This can be done easily thanks to the fact that the *constructor* for the `List<T>` class **allows you to pass an array** for initialising purposes. That way you would avoid the iteration you mention. 😉 

```typescript
let arrayOfIncidents: Incident[] = [ /* ... array of Incident objects you already have... */ ];
let listOfIncidents = new List<Incident>(arrayOfIncidents); // this is what you actually want
```

Hope that helps!
