### ISSUE TITLE
Disticnt() does not work correctly

### ISSUE THREAD

**Issue by SkeletonSkelettron** [kutyel/linq.ts#148]
Hi
Distinct() function is not working correctly.
You can check this code:
`const store1 = new List<Product>([
      new Product({ Name: 'apple', Code: 9 }),
      new Product({ Name: 'orange', Code: 4 }),
      new Product({ Name: 'apple', Code: 9 }),
      new Product({ Name: 'lemon', Code: 12 })
    ]);

    console.log(store1.Distinct().ToArray());`

this outputs 
`0: Product {Name: "apple", Code: 9}
1: Product {Name: "orange", Code: 4}`
it lacks third object - { Name: 'lemon', Code: 12 }.

So, I suggest you to change the implementation to following: 

instead of using custom findindex function
`    return this.Where(
      (value, index, iter) =>
        (isObj(value)
          ? findIndex(obj => equal(obj, value))(iter)
          : iter.indexOf(value)) === index
    )`
use javascript function Array.prototype.findIndex: 
`    return this.Where(
      (value, index, iter) =>
        (isObj(value)
          ? iter.findIndex(obj=> equal(obj,value))
          : iter.indexOf(value)) === index
    )`

then Distinct works like charm and you can remove extra function from the code :) 

ps.
your implementation works correctly for following array 
 const store1 = new List<Product>([
      new Product({ Name: 'apple', Code: 9 }),
      new Product({ Name: 'orange', Code: 4 }),
      new Product({ Name: 'apple', Code: 9 }),
      new Product({ Name: 'lemon', Code: 12 }),
      new Product({ Name: 'lemon', Code: 12 })
    ]);
but not for the one above 

p.p.s
 I forked this library and made it work for any typed array by prototyping ;) 
https://github.com/SkeletonSkelettron/Linq-Typed

**Comment by kutyel** [comment]
Hi! Thanks for reporting the issue! I’ll fix this and publish a new release tonight! 😉

**Comment by kutyel** [comment]
Or if you want you can provide a PR and that way I can add you as  a contributor to the library! 🎉

**Comment by SkeletonSkelettron** [comment]
thanks kutyel, I will :)))
