### ISSUE TITLE
Lack of List<T>.Remove Method

### ISSUE THREAD

**Issue by twoeo** [kutyel/linq.ts#15]
As title say,

lacking of Remove method as :

https://msdn.microsoft.com/en-us//library/cd666k3e(v=vs.110).aspx

**Comment by kutyel** [comment]
Added to roadmap, do you actually need the `List<T>.Remove()` method **passing exactly the object you want to remove** or would it be more useful just to add the `List<T>.RemoveAt()` method to just delete it **given the index of the item**?

**Comment by twoeo** [comment]
Maybe I need **list.Remove((v,i)=>boolean)** more.

RemoveAt can achieve by array.splice.

I use this currently:

```
    Array.prototype.remove = (filter:(v,i,arr)=>boolean){
        for(let i=this.length-1; i>-1; --i){
            filter(this[i],i,this) && this.splice(i,1);
        }
    }
```

**Comment by kutyel** [comment]
I think that, in order to be consistent, I will add the following methods to close this issue:
- `List<T>.IndexOf()`
- `List<T>.RemoveAt()`
- `List<T>.Remove()`

In order to implement the function like this:
```typescript
public Remove(item: T): boolean {
    return this.RemoveAt(this.IndexOf(item));
}
```
