### ISSUE TITLE
Browser support information needed

### ISSUE THREAD

**Issue by fahadash** [kutyel/linq.ts#150]
The docs need to be updated with the list of supported browsers. Is there a place where we can find this information?

**Comment by kutyel** [comment]
Hi, the compilation target is `es5`, therefore the compatibility table is this one: http://kangax.github.io/compat-table/es5/, feel free to add it to the README.md in a PR or provide it some other way to the repo 😉

**Comment by fahadash** [comment]
Are you sure your target is ES5? I downloaded the package from NPM and .js files have “class” keyword used widely.

**Comment by kutyel** [comment]
Absolutely sure! I just opened the `dist` folder (which is the one being published) and there are several files depending on the consumer, have a look at the picture:
<img width="292" alt="dist" src="https://user-images.githubusercontent.com/5127501/48184111-4a0bf380-e331-11e8-93eb-99bbb829634b.png">
I think the one you should be concerned about is the `*.umd.js` version (for browsers) and that one does not contain any classes 😉

**Comment by fahadash** [comment]
Thank you. I have tried typescript-linq which is not es5 compliant. Tried line-es5 which is buggy, I am going to give this one a try now.
