### ISSUE TITLE
ionic 3 Android/IOS Mobile Linq not working

### ISSUE THREAD

**Issue by 009topersky** [kutyel/linq.ts#158]
Thanks to this library makes my life easier 

BUT..
Currently, I have a project running on ionic 3 + Angular 5

The problem is when i build the application on Android/IOS Device, the linq query is not working

Please HELP Me!
Thanks

**Comment by kutyel** [comment]
Hi! I'm sorry this question is too vage and scarce on details, can you please elaborate more? :)
