### ISSUE TITLE
I hit an Unexpected token. (NG2 Project)

### ISSUE THREAD

**Issue by wupaz** [kutyel/linq.ts#16]
Compile work but when I run I got :
```
zone.js:323 Error: SyntaxError: Unexpected token <at Object.eval 
(http://localhost/fusion/app/component/common/floatingCombo.component.js:23:16)
--> var linqts_1 = require('linqts');
```

Webpack install is necessary? 

And btw why you didn't supply `.js`?

**Comment by kutyel** [comment]
Could you add the **steps** you follow to reproduce the error? What tutorial of Angular 2 are you following? Maybe if I am able to reproduce it I will be able to fix it. Thanks in advance!

**Comment by kutyel** [comment]
I thinks it is about time to close this issue by lack of reponse. I cannot solve a bug I do not know how to reproduce.
