### ISSUE TITLE
SyntaxError: Unexpected token `export`

### ISSUE THREAD

**Issue by mjknight50** [kutyel/linq.ts#163]
Node v10.15.3

Imported like this:
```sh
import { List } from 'linqts';

myproject/node_modules/linqts/dist/index.js:10
[0] [1] export { default as List } from './src/list';
[0] [1] ^^^^^^
[0] [1] 
[0] [1] SyntaxError: Unexpected token export
[0] [1]     at new Script (vm.js:80:7)
[0] [1]     at createScript (vm.js:274:10)
[0] [1]     at Object.runInThisContext (vm.js:326:10)
[0] [1]     at Module._compile (internal/modules/cjs/loader.js:664:28)
[0] [1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
[0] [1]     at Module.load (internal/modules/cjs/loader.js:600:32)
[0] [1]     at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
[0] [1]     at Function.Module._load (internal/modules/cjs/loader.js:531:3)
[0] [1]     at Module.require (internal/modules/cjs/loader.js:637:17)
[0] [1]     at require (internal/modules/cjs/helpers.js:22:18)
```

Here is my tscconfig.json:

```json
{
  "compilerOptions": {
    "declaration": false,
    "noUnusedLocals": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": [
      "es2017",
      "dom"
    ],
    "removeComments": false,
    "sourceMap": true,
    "mapRoot": "../dist/",
    "module": "commonjs",
    "moduleResolution": "node",
    "outDir": "../dist/",
    "target": "es2016",
    "allowJs": false,
    "typeRoots": [
      "../node_modules/@types"
    ],
    "baseUrl": "."
    
  }
}
```

**Comment by aequasi** [comment]
This broke since 1.12.2.

@mjknight50 if you roll back to 1.12.2, it should work

**Comment by mjknight50** [comment]
@aequasi  Thanks for the response..  do you mean broken since 1.12.5?

**Comment by aequasi** [comment]
I don't know when it broke, but it was working in 1.12.2, so it broke at some point since then

**Comment by gruckion** [comment]
Can you please format your code, you can use back ticks ` 3 of them wrapped around your code so it is easier to read.

**Comment by kutyel** [comment]
@mjknight50 @aequasi @gruckion can you please check if it works with the latest release and also like the library if you haven’t already? 😊

**Comment by arunesh90** [comment]
Still broken over here. As you can see at https://unpkg.com/linqts@1.12.6/dist/index.js it's still using `export`

**Comment by kutyel** [comment]
Which node version are you using? I tried on a small project locally with the latest LTS version and it worked fine 🤔

**Comment by mjknight50** [comment]
This is definitely still broken for 1.12.6

**Comment by kutyel** [comment]
K, will fix it as soon as I have time, if you guys can provide a working PR that would be awesome 😎

**Comment by DmitryEfimenko** [comment]
any updates on this?

**Comment by mrsauravsahu** [comment]
I can check it out this weekend. 😁

**Comment by mrsauravsahu** [comment]
Yes, even I can reproduce the error with v10.15.3. Isn't this happening because @kutyel you are targeting esnext in your `tsconfig.json`? Better to compile down to ES5 with typings separately, so that the consumer can easily use with TypeScript or JavaScript. Thoughts?

**Comment by kutyel** [comment]
Sure, I'll try to do that today, thanks.

**Comment by kutyel** [comment]
Also, @mrsauravsahu feel free to provide a PR if you want to contribute! 😉

**Comment by mrsauravsahu** [comment]
Sure @kutyel 😬

**Comment by mrsauravsahu** [comment]
So, here's what I did. Cloned your project and ran `npm run build` to get the `dist` folder. Created a typeScript project and imported the `index.js` folder from the dist generated. The TS project ran without any errors.
The issue is indeed the way you are publishing to npm. I couldn't find a publish command in your package.json. I can open up a PR, but essentially what we need to do, is to publish the contents of the dist folder, which has all TypeScript imports compiled down to node requires

**Comment by kutyel** [comment]
Sure, feel free to add whatever is needed, my issue has always have been ava and the way it all transpiles to js, either the package is wrong or the tests are wrong, and sincerely don't have any more time to waste on this, thanks for your help!

**Comment by mrsauravsahu** [comment]
I don't see a CD file.  Are you deploying manually to npm?
In that case, can you send me the command you're using.

**Comment by kutyel** [comment]
`npm publish`?

**Comment by kutyel** [comment]
I think I've finally been able to fix this by removing microbundle and simple using `tsc`, https://github.com/kutyel/linq.ts/commit/3855a3d621de08e14abbec13acb2ff8272f8ad88 it will be fixed in next version: **v1.13** and I will close this ticket as soon as I'm able to publish the package to npm, who lost my credentials, thanks everyone for the patience!

**Comment by kutyel** [comment]
This should be fixed now that the v1.13 is released to npm, please someone try it out and tell me if it works 😉

**Comment by jaredbaszler** [comment]
FYI - I still got this error today with the most recent version of of the package at this time (1.14.3).  I rolled back to 1.12.2 and the error disappeared.

**Comment by kutyel** [comment]
Hi, can you provide steps to reproduce please? There is no longer a bundling step so this definitely should not happen 😄

**Comment by jaredbaszler** [comment]
I installed `1.14.3` today and then just ran a simple where clause:

```
const result = new List(posData)
    .Where(a => a?.SKUName?.toLowerCase().includes('myProduct') === true)
```

my `tsconfig.json` is: 

```{
  "compilerOptions": {    
    "target": "ES2017",
    "module": "commonjs",
    "lib": [
      "es6"
    ],
    "allowJs": true,
    "declaration": true,
    "sourceMap": true,
    "outDir": "build",
    "rootDir": "",
    "strict": true,
    "noImplicitAny": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "resolveJsonModule": true,
    "forceConsistentCasingInFileNames": true 
  },
  /* Exclude certain directories when building */
  "exclude": [
    "./node_modules",
    "./big_box_data_transfer_frontend",
    "./build"
  ],
}```

I'm rather new to node.js and typescript so if there is more I can provide to help identify, let me know and I will include.

**Comment by mjknight50** [comment]
This still is happening.
"linqts": "^1.14.3",

**Comment by kutyel** [comment]
@jaredbaszler @mjknight50 feel free to provide a PR, I'll be happy to merge, tried `microbundle` in the past but could not make it to work as expected with TypeScript 😓
