### ISSUE TITLE
.ForEach with thisArg

### ISSUE THREAD

**Issue by janseng1970** [kutyel/linq.ts#164]
Hello,

I am working with your library, thanks for the possibility.

I am using the List<> generic as class property type. In case I have to do a loop in a class methode I am runnig in the this problem in context of the .ForEach(callback). The .ForEach wrapper ist not supporting the thisArg of the javascript .forEach function of an array.

Would it not a good enhancemend if ist would be possible to write something like:
```ts
public Methode(): void
    this.ListProperty.ForEach((element) => { 
          ....
          this.SomeProperty
          ....
    }, this);
}
```
instead of:
```ts
public Methode(): void
    this.ListProperty.ToArray().forEach((element) => { 
          ....
          this.SomeProperty
          ....
    }, this);
}
```
I know this is not original Linq, but in my opinion any solution for this "this - context" problem will be javascript specific anyway.

Thanks and regards,

Georg

**Comment by kutyel** [comment]
Hi! Thanks for opening an issue, besides this not being the behaviour of LinQ (which this library tries to imitate), any problem with **this** in JavaScript is solved by using arrow functions `=>`, hence, it should not be necessary to do strange tricks! 😉
