### ISSUE TITLE
Index '[]' operator not behaving as expected.

### ISSUE THREAD

**Issue by Univac1107** [kutyel/linq.ts#166]
Hello, in the following code:

`const list = new List([1, 2, 3, 4, 5]);`
`const a = list[2];`

'a' is undefined instead of 3. Is this the expected behavior? Should I use ToArray() first?

Thanks!

**Comment by kutyel** [comment]
It is the intended behaviour, you should use `List.ElementAt(2);` to achieve what you want 😉
