### ISSUE TITLE
Expression Func

### ISSUE THREAD

**Issue by petrck** [kutyel/linq.ts#17]
Hello, first of all, great project, thank you for it. 

I would like to ask, if is possible to do something like this in C#: 

```cs
public static Expression<Func<Actuality, ActualityViewModel>> ToModel()
{
    return s => new ActualityViewModel
        {
            Id = s.Id,
            ...
        }
}
```

And later in select: ... `Select(MyClass.ToModel()).First()`... etc.

Is there way, how to select properties to model with using LinQ.ts?

Thanks for your answer!

**Comment by kutyel** [comment]
Seems quite easy to make the same in TypeScript, you just have to switch your mind and know that you are in the JavaScript world 😄  Maybe if you put this method in context or explain what do you really want it for I will be able to give you an approximation 😉

**Comment by petrck** [comment]
@kutyel ok, let's look to this situation. I have this array:

```
"pages": [
  "name": "Petr",
    "nextProp": "etc...",
  "sections": { "name":  "home", "pattern": "/home" }, { "name":  "about", "pattern": "/about" }
],
[
  "name": "Martin",
  "nextProp": "etc...",
  "sections": { "name":  "home", "pattern": "/home-xx" }, { "name":  "blog", "pattern": "/blog" }
]
```

here is using interface object IPageModel:

```
interface IPageModel {
      name: String;
      sections: Array<ISectionModel>; //or List<ISectionModel> - doesn't matter for me
}
```

ISectionModel has only _name_ and _pattern_ string property

Now, I need to select by name and get only _sections_ and _name_ :
`var page = new List<IPageModel>(pages).Where(s => s.name == "Petr").Select(._..here I need property select_).FirstOrDefatult();
`
And this is all. A just need to select only two property. In C# for example:

...Select(p => new PageModel {
     name = p.name,
    sections = p.sections.Select(s => new SectionModel {
         name = s.name,
         pattern = s.pattern 
    })
}).FirstOrDefault();

How Can I correctly solve this problem in javascript (Typescript) and LinQ.ts ?
Thank you.

**Comment by kutyel** [comment]
@petrck I am glad you were able to find an answer to your question, it was a matter of LINQ knowledge in the end 😉
