### ISSUE TITLE
Support TypeScript in Strict mode

### ISSUE THREAD

**Issue by kutyel** [kutyel/linq.ts#170]
Right now there are quite a few type errors (especially regarding predicate functions) if you enable the strict mode of TypeScript, the goal is to fix all those to make the library more type-safe.

```json
{
  "strict": true
}
```

Since this is a breaking change, fixing this issue will provoke the release of a **v2.0.0 version.**

**Comment by rustycoslett** [comment]
Does this mean that going from 1.12.6 to 1.13.0 should fail with strict?  I updated today and get an error that cannot find .d.ts from index.  Had to rollback to 1.12.6

**Comment by kutyel** [comment]
Nope, I intend to make the strict version of the library a 2.0.0 (breaking change), but that has not happened yet. The typings now should be at `types/index.d.ts`, if more people has this problem I'll make another release outputting the typings to the same folder as the js code :)

**Comment by TheCleric** [comment]
I am also having this issue:
```
src/index.ts:1:22 - error TS7016: Could not find a declaration file for module 'linqts'. 

'/Users/user/Dev/project/node_modules/linqts/dist/index.js' implicitly has an 'any' type.

  Try `npm install @types/linqts` if it exists or add a new declaration (.d.ts) file containing `declare module 'linqts';`
```

**Comment by kutyel** [comment]
Hi @TheCleric and @rustycoslett, in the latest version of the library https://github.com/kutyel/linq.ts/releases/tag/v1.14.0 I've changed the type declarations back to the dist folder, if the issue persists please **open a different issue**, this one is to track progress of when the library will be 0.2 and support TypeScript's Strict Mode.

**Comment by maxime-aubry** [comment]
Hello.
Will the version 2.0 available soon ?
I am stuck on my project because i am using strict mode.
Thanks.

**Comment by kutyel** [comment]
Contributions are welcome, I still maintain the lib but TBH supporting strict mode requires quite a bit of changes 😟
