### ISSUE TITLE
package.json incorrect in 1.14.0

### ISSUE THREAD

**Issue by marlon-tucker** [kutyel/linq.ts#172]
Hello,

The `package json` says the files should be in `dist/` but they are now in `dist/src/`.

https://github.com/kutyel/linq.ts/blob/eb9d8997fd9a1aa70b33232c099bf2162e9d938d/package.json#L7-L8

**Comment by marlon-tucker** [comment]
Hi, the `main` entry point also need to be changed so bundlers can locate the entry file.

**Comment by kutyel** [comment]
Thanks, not it should be fixed in https://github.com/kutyel/linq.ts/releases/tag/v1.14.2 😉
