### ISSUE TITLE
Extend array prototype

### ISSUE THREAD

**Issue by HypeillingerChillinger** [kutyel/linq.ts#174]
Say we have an array and we want to use LINQ methods on it. Then we have to instantiate a new List.
It would be more convenient if the array prototype was extended. Is that possible?

```typescript
const myArray: Car[] = [];
const ordered = new List(myArray).OrderBy(x => x.color).ToArray();

// better:
const ordered = myArray.OrderBy(x => x.color);


```

**Comment by kutyel** [comment]
That is a mistake and should never be done: https://stackoverflow.com/questions/14034180/why-is-extending-native-objects-a-bad-practice
