### ISSUE TITLE
.ToDictionary should return a Dictionary<TKey, TValue>

### ISSUE THREAD

**Issue by Jonatthu** [kutyel/linq.ts#177]
https://github.com/kutyel/linq.ts/pull/136

This is not allowing me to use the following syntax: 

```typescript
const questions = new List<PCSQuestion>([]);
const questionDic = questions.ToDictionary((x) => x.id);
const questionDicProperty = questionDic[''].something;
```

**Comment by kutyel** [comment]
Hi, are you sure you are using the function correctly?
Have a look at the tests:
```typescript
  const dictionary = people.ToDictionary(x => x.Name)
  t.deepEqual(dictionary['Bob'], { Age: 50, Name: 'Bob' })
  t.is(dictionary['Bob'].Age, 50)

  const dictionary2 = people.ToDictionary(x => x.Name, y => y.Age)
  t.is(dictionary2['Alice'], 25)
  // Dictionary should behave just like in C#
  t.is(dictionary.Max(x => x.Value.Age), 50)
  t.is(dictionary.Min(x => x.Value.Age), 15)
  const expectedKeys = new List(['Cathy', 'Alice', 'Bob'])
  t.deepEqual(dictionary.Select(x => x.Key), expectedKeys)
  t.deepEqual(dictionary.Select(x => x.Value), people)
```
They are working correctly, and if not, please provide a unit tests that fails so that we can fix it :)

**Comment by Jonatthu** [comment]
@kutyel 
This is what I get when I try in typescript 4.1.2
![image](https://user-images.githubusercontent.com/3742176/104780604-eada7280-5735-11eb-9bc8-18fa68512652.png)

**Comment by Jonatthu** [comment]
<img width="554" alt="Screen Shot 2021-01-15 at 1 32 23 PM" src="https://user-images.githubusercontent.com/3742176/104780742-1a897a80-5736-11eb-86a0-847302af33bb.png">

**Comment by Jonatthu** [comment]
I believe the typing is incorrect

**Comment by kutyel** [comment]
I believe you are passing the wrong function to `ToDictionary`, whatever you pass there will become the `Key` of your Dictionary...

**Comment by kutyel** [comment]
If you want a `Dict<{ id: string }, { name: string }>`, consider using the function `peopleList.ToDictionary(x => x.id, y => y.name)`...

**Comment by Jonatthu** [comment]
@kutyel Actually my issue is not the typing is incorrect on the Key, the problem is that the typing that is displaying does not have the ability to access to the dictionary by using the myDictionary['myKey'] syntax just like c#

**Comment by kutyel** [comment]
As I said, please provide a unit test with a complete example with types and the input and output that you expect and that way we will know if this is something that needs to be fixed 😅

**Comment by Jonatthu** [comment]
<img width="780" alt="Screen Shot 2021-01-15 at 1 40 08 PM" src="https://user-images.githubusercontent.com/3742176/104781350-2fb2d900-5737-11eb-8aa3-f892f3423f4c.png">

This is on c#

**Comment by Jonatthu** [comment]
The unit tests will not give me a wrong result.
This is a typing issue for Typescript @kutyel

**Comment by Jonatthu** [comment]
The typing 
```
const peopleDict: List<{
    Key: string;
    Value: {
        id: string;
        name: string;
    };
}>
```

That the ToDictionary function is returning is wrong.

It should be similar to:

{ [key:string]: T }

**Comment by Jonatthu** [comment]
@kutyel These are the typescript definitions, they are incorrect on this library. It should be reverted and support instead .Keys and Values methods if preferred.
```
    ToDictionary<TKey>(key: (key: T) => TKey): List<{
        Key: TKey;
        Value: T;
    }>;
    ToDictionary<TKey, TValue>(key: (key: T) => TKey, value: (value: T) => TValue): List<{
        Key: TKey;
        Value: T | TValue;
    }>;
```

The right typing for a dictionary should be

```
    ToDictionary<TKey>(key: (key: T) => TKey): { [key: TKey]: T };
    ToDictionary<TKey, TValue>(key: (key: T) => TKey, value: (value: T) => TValue):  { [key: TKey]: T | TValue };;
```

**Comment by kutyel** [comment]
Ahhhh... I see what you mean, so the response should be like a JS object, like what ToLookUp does:
```typescript
  /**
   * Creates a Lookup<TKey, TElement> from an IEnumerable<T> according to specified key selector and element selector functions.
   */
  public ToLookup<TResult>(
    keySelector: (key: T) => string | number,
    elementSelector: (element: T) => TResult
  ): { [key: string]: TResult[] } {
    return this.GroupBy(keySelector, elementSelector)
  }
```
Strange that nobody else complained about this before 🤔

**Comment by Jonatthu** [comment]
Maybe the library can add an extra extension, just for the typing since I like the fact we can have Key and Value

**Comment by kutyel** [comment]
@Jonatthu Any reason why this comments is not valid anymore https://github.com/kutyel/linq.ts/issues/126#issuecomment-388589341? 🤔

**Comment by kutyel** [comment]
I'm closing this for the moment, because if I change back the Dictionary<TKey, TValue>, this code will break:
```typescript
  // Dictionary should behave just like in C#
  t.is(dictionary.Max(x => x.Value.Age), 50)
  t.is(dictionary.Min(x => x.Value.Age), 15)
```
Which would be a major change, and if people wants a JS object instead you can use the `ToLookUp` function instead.

**Comment by schotime** [comment]
The only problem here is that ToLookup returns an TResult[] instead of just a TResult. Can we have a another overload that does this?

**Comment by schotime** [comment]
A sample implementation is

```ts
function ToDictionaryLookup<T, TRet>(items: T[], id: (item: T) => string, value: (item: T) => TRet) {
    return items.reduce((r, x) => ({ ...r, [id(x)]: value(x) }), {} as { [id: string]: TRet });
}
```
