### ISSUE TITLE
module and namespace collision

### ISSUE THREAD

**Issue by nanivijay** [kutyel/linq.ts#18]
we are following namespace in the ts files and the linq.ts has module declarations. I can't import the modules because of the modules and namespaces are not working together. could you please help me how can i consume linq.ts module inside namespace?

**Comment by kutyel** [comment]
@nanivijay Did you manage to solve the problem yourself? Could you explain here what you did to solve it so that others can benefit from it? Thanks in advance! :smile:

**Comment by nanivijay** [comment]
@kutyel No :( I didn't. After going through most of the documentation on modules and namespaces i thought it's not the issue with the linqts package and closed the issue. If wrapped the linq.ts inside namespace , then i am able to use the linq methods .

**Comment by kutyel** [comment]
@nanivijay That's right, it is not a good practice to mix **es2015** modules with namespaces, this last ones having a recent tendency to disappear! :wink:

**Comment by nanivijay** [comment]
@kutyel why don't you wrap the linq.ts inside a namespace? 
for eg: https://github.com/brunolm/LinqSharp/blob/master/src/linqsharp.ts

Is there any issues in wrapping inside a namespace?

**Comment by kutyel** [comment]
Because namespaces are disappearing from the TypeScript scene, beeing replace by **es2015** modules, as I said before. If you have a look on real world projects, like [Angular](https://github.com/angular/angular) or [NativeScript](https://github.com/NativeScript/NativeScript) you will see what is the tendency right now...

**Comment by nanivijay** [comment]
@kutyel thanks for the information.

**Comment by kutyel** [comment]
@nanivijay BTW: you can support the project by giving it a :star: in GitHub! :tada:

**Comment by kutyel** [comment]
@nanivijay [here](https://www.typescriptlang.org/docs/handbook/modules.html#do-not-use-namespaces-in-modules) is more information related to this topic, in case anyone wants to know more.
> **A note about terminology**: It’s important to note that in TypeScript 1.5, the nomenclature has changed. “Internal modules” are now “namespaces”. “External modules” are now simply “modules”, as to align with ECMAScript 2015’s terminology, (namely that `module X {` is equivalent to the now-preferred `namespace X {`).

**Comment by nanivijay** [comment]
@kutyel Thanks for the link. I went through them :)
