### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by xxxjnx** [kutyel/linq.ts#180]
I introduce  import { List } from '../node_modules/linqts/dist/src/index.js';  And use List ,The error displayed is Uncaught SyntaxError: The requested module '../node_modules/linqts/dist/src/index.js' does not provide an export named 'List'

**Comment by kutyel** [comment]
Hi! Can you please provide steps to reproduce? node/web? angular? react? This issue should definitely be closed by https://github.com/kutyel/linq.ts/issues/175

**Comment by xxxjnx** [comment]
I'm a beginner. The new error after configuration according to your tsconfig.json file is demo.js:2 uncaugh referenceerror: exports is not defined

at demo.js:2   ;  This sentence in the document,  Object.defineProperty(exports, "__esModule", { value: true });

This is mine tsconfig.json file configuration
`{
    "compilerOptions": {
        "target": "es5",
        "module": "CommonJS",
        "sourceMap": true,
        "outDir": "./js",
        "moduleResolution": "node",
        "typeRoots": ["node_modules/@types"],
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "lib": ["es2015", "es2016", "es2017", "dom"],
        "declaration": true,
        "allowSyntheticDefaultImports": true,
        "declarationDir": "dist"
    }
}
`

**Comment by xxxjnx** [comment]
I'm a beginner. The new error after configuration according to your tsconfig.json file is demo.js:2 uncaugh referenceerror: exports is not defined

at demo.js:2   ;  This sentence in the document,  Object.defineProperty(exports, "__esModule", { value: true });

This is mine tsconfig.json file configuration
`{
    "compilerOptions": {
        "target": "es5",
        "module": "CommonJS",
        "sourceMap": true,
        "outDir": "./js",
        "moduleResolution": "node",
        "typeRoots": ["node_modules/@types"],
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "lib": ["es2015", "es2016", "es2017", "dom"],
        "declaration": true,
        "allowSyntheticDefaultImports": true,
        "declarationDir": "dist"
    }
}
`

**Comment by kutyel** [comment]
Hi! Please copy the tsconfig.json mentioned in https://github.com/kutyel/linq.ts/issues/163 and it should work 😉
