### ISSUE TITLE
[Question] What Linq queries do you support so far?

### ISSUE THREAD

**Issue by bastienJS** [kutyel/linq.ts#19]
I am just looking for a good linq.net implementation done in TS.

Would you please be that kind and put a list of linq.net supported queries you have done so far on your main page?

Looking at your source code quickly I like it groupby,intersect,except all there :-)

**Comment by kutyel** [comment]
Hi @bastienJS! If you have a look at the [tests](https://github.com/kutyel/linq.ts/blob/master/test/list.ts), you will see that there is pretty much everything of the LINQ spec covered and at least one example for each, that should be enough! :wink:

PD: If you liked the library, don't forget to give it a :star: in GitHub! 👍

**Comment by kutyel** [comment]
@bastienJS ping... :)

**Comment by kutyel** [comment]
The [documentation](http://kutyel.github.io/linq.ts/docs/classes/list/index.html) of the project is enough clear about the implementation of the LINQ spec.
