### ISSUE TITLE
String Representations of Query Possible

### ISSUE THREAD

**Issue by vanthome** [kutyel/linq.ts#20]
Is it possible to obtain a string representation of a query as discussed here?:

http://stackoverflow.com/questions/30997682/getting-source-of-linq-query-and-serialize-to-string

Maybe even to parse a stringed query into a query?

**Comment by kutyel** [comment]
I am sorry this is a LinQ **to Objects** implementation, there is no SQL query behind, nor any integration with any kind of database.
