### ISSUE TITLE
Cannot import TypeScript module

### ISSUE THREAD

**Issue by sn3h** [kutyel/linq.ts#21]
Hi I get unexpected token export while trying to use `List<T>`...

```typescript
import { List } from 'linqts';
let arr = new List<number>([1,2,3,4,5])
    .Where(x => x > 3)
    .Select(y => y * 2)
    .ToArray(); // > [8, 10] 
console.log(arr);
```
console log: 
```
linq.ts:10 Uncaught SyntaxError: Unexpected token export
exports.runInThisContext @ vm.js:53Module._compile @ module.js:511Module._extensions..js @ module.js:550Module.load @ module.js:456tryModuleLoad @ module.js:415Module._load @ module.js:407Module.require @ module.js:466require @ internal/module.js:20(anonymous function) @ app.js:5Module._compile @ module.js:541Module._extensions..js @ module.js:550Module.load @ module.js:456tryModuleLoad @ module.js:415Module._load @ module.js:407Module.require @ module.js:466require @ internal/module.js:20(anonymous function) @ index.html:18
```
using `node tsc -w`

tsconfig.json
```json
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es6",
        "noImplicitAny": true,
        "sourceMap": false
    },
    "exclude": [
        "node_modules"
    ]
}
```
es3, es5 does not make any difference

Got no idea what am I doing wrong :confused:

**Comment by kutyel** [comment]
Thank you for submitting this bug! This used to work a couple versions ago... you can fix it if you manually compile the library to `.js` and then use it (BTW: do you want to use LINQ for node or for the browser? If it is the browser, have a look at the https://github.com/kutyel/linq.ts/blob/master/readme.md).

I will close this when I provide a good-for-everything solution whether I have to provide the compiled js files with the npm install or not.
