### ISSUE TITLE
wrong sorting with multiple ThenBy's

### ISSUE THREAD

**Issue by jbrekle** [kutyel/linq.ts#22]
Hi,
I tried using your library but I have a issue with multiple ThenBy's - it seems the last ThenBy has precendence over the first when it shouldn't.

```typescript
let unsorted = new List([
    {a:2, b:1, c:1},
    {a:1, b:2, c:2},
    {a:1, b:1, c:3}
]);
let sorted = unsorted.OrderBy(x => x.a)
    .ThenBy(x => x.b)
    .ThenBy(x => x.c)
    .ToArray();
```

I constructed the example in a way that without the last ThenBy, the items should be sorted reversed. The last ThenBy should have no effect because there are no equalities in the first two sort steps. But it does.
Is there something wrong in my logic or is this a bug?

Regards,
Jonas

**Comment by kutyel** [comment]
Hi @jbrekle! I would have to look at the code... but the `ThenBy()` function was far the **trickyest** to implement, so it might be a bug. Thanks for reporting it!

**Comment by jbrekle** [comment]
Thanks for the fast reply. 
I also checked with .NET:

```cs
public class ThenByTester
    {
        private class O
        {
            public int A;
            public int B;
            public int C;
        }

        [Test]
        public void TestThenBy()
        {
            var unsorted = new List<O>()
            {
                new O {A = 2, B = 1, C = 1},
                new O {A = 1, B = 2, C = 2},
                new O {A = 1, B = 1, C = 3}
            };
            var sorted = unsorted.OrderBy(x => x.A)
                .ThenBy(x => x.B)
                .ThenBy(x => x.C)
                .ToArray();
        }
    }
```

That is sorted as I expect.
