### ISSUE TITLE
Fix module for browser/node

### ISSUE THREAD

**Issue by Meai1** [kutyel/linq.ts#26]
d:\TypeScriptSamples\warship>webpack
Hash: 396f0bfb9d565b6f60f0
Version: webpack 1.13.2
Time: 29ms

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./app.ts in d:\TypeScriptSamples\warship

d:\TypeScriptSamples\warship>

**Comment by kutyel** [comment]
I think this might be due to the fact that I change the location of the compiled `.js` files, should be easy to fix. I will give it a go when I have a sec.

**Comment by Meai1** [comment]
no i just had to name it app.ts, but i still couldnt get it to work. i included the generated bundle.js but the tsc compiler still complained about not finding the linqts module

**Comment by Kurtz1993** [comment]
Please check PR #27 that could be the fix for this issue

**Comment by Kurtz1993** [comment]
Hmm... maybe needs some work, will be testing more tonight

**Comment by kutyel** [comment]
Fixed in #27, thanks @Kurtz1993!
