### ISSUE TITLE
Implement SkipWhile()

### ISSUE THREAD

**Issue by kutyel** [kutyel/linq.ts#3]
Implement the [method](https://github.com/kutyel/linq.ts/blob/68cdfaf63ad66512fac15f0410d75dab15ef75e5/linq.ts#L291-L296) according to the following [docs](https://msdn.microsoft.com/es-es/library/bb549075(v=vs.110).aspx):

```cs
int[] grades = { 59, 82, 70, 56, 92, 98, 85 };

IEnumerable<int> lowerGrades =
    grades
    .OrderByDescending(grade => grade)
    .SkipWhile(grade => grade >= 80);

Console.WriteLine("All grades below 80:");
foreach (int grade in lowerGrades)
{
    Console.WriteLine(grade);
}

/*
 This code produces the following output:

 All grades below 80:
 70
 59
 56
*/
```

The unit test for this method is ready to be [uncommented](https://github.com/kutyel/linq.ts/blob/68cdfaf63ad66512fac15f0410d75dab15ef75e5/test/list.ts#L217-L220) when this issue closes.

**Comment by keropodium** [comment]
![tv-shows-father-ted-jack-l7ZrjLJsznQuQ](https://camo.githubusercontent.com/40927f5f7f455db26be10f7cddcedbfc48c0a646/68747470733a2f2f6d65646961332e67697068792e636f6d2f6d656469612f6c375a726a4c4a737a6e5175512f67697068792e676966)
