### ISSUE TITLE
add to Primitive extension method

### ISSUE THREAD

**Issue by HarelAshwal** [kutyel/linq.ts#33]
LK"I

Hi,

Have you considered adding toPrimitive extension method?
In that case , we can easily convert the LINQ List object into TypeScript array primitive.

Harel

**Comment by kutyel** [comment]
Hi!

That is what the [`.ToArray()`](https://github.com/kutyel/linq.ts/blob/2bc4e4b78f0c32ba9a5ae09883967d8d3a7f110f/test/list.ts#L491-L493) function is for! :wink:

Greetings,

kutyel.
