### ISSUE TITLE
First should throw if no elements in list

### ISSUE THREAD

**Issue by mtauzin** [kutyel/linq.ts#34]
Like the Single function that throws an error when there are not exactly 1 element in the list,, the First (and also Last) function should throw if the list is empty and the ElementAt function should also throw if the provided index exceeds the list length.

**Comment by kutyel** [comment]
Can you please back up that with links to the LINQ reference page? 😉  I'd be happy to mark it as a bug and fix it (if you don't feel like making a PR yourself) 😄

**Comment by mtauzin** [comment]
Here are the links : 
[First](https://msdn.microsoft.com/fr-fr/library/bb291976(v=vs.110).aspx) 
[Last](https://msdn.microsoft.com/fr-fr/library/bb358775(v=vs.110).aspx)
Exceptions : InvalidOperationException : The source sequence is empty.

[ElementAt](https://msdn.microsoft.com/fr-fr/library/bb299233(v=vs.110).aspx)
Exceptions : ArgumentOutOfRangeException : index is less than 0 or greater than or equal to the number of elements in source.

**Comment by kutyel** [comment]
Thanks!
