### ISSUE TITLE
First() and FirstOrDefault() returns T | Error

### ISSUE THREAD

**Issue by JPaulDuncan** [kutyel/linq.ts#38]
I'm having issues where I expect:

```typescript
private _foo: MyThing;
private _fooList: List<MyThing>;
get Foo(){return _foo;}
set Foo(value : MyThing){ _foo = value;}
DoStuff(){
 Foo = this._fooList.FirstOrDefault(x=> x.id == 1);
}
```

DoStuff() doesn't work because `this._fooList.FirstOrDefault()` isn't returning MyThing, it's returning `MyThing | Error`. 

Or am I misusing this thing?

**Comment by kutyel** [comment]
You are right, the `OrDefault()` part of the function should handle the exceptions, according to the [docs](https://msdn.microsoft.com/en-us/library/bb340482(v=vs.110).aspx). This is an easy fix though, and will do in no time 😉  👍

**Comment by JPaulDuncan** [comment]
Also, it throws the "The source sequence is empty" if the predicate returns no items for First():

private _foo: MyThing;
private _fooList: List<MyThing>;
get Foo(){return _foo;}
set Foo(value : MyThing){ _foo = value;}
DoStuff(){
 Foo = this._fooList.FirstOrDefault(x=> x.id == "asdf"); // THERE IS NO "asdf" element in _fooList -- Exception
}

-- This is happening with the if()..else() in the First() function.
