### ISSUE TITLE
cannot find module.

### ISSUE THREAD

**Issue by lorenlew** [kutyel/linq.ts#39]
I had to change to  
  "typings": "dist/linq.d.ts" instead of   
  "typings": "linq.ts" 
in **package.json** in order to find the module with 
import { List } from 'linqts'; in the typescript file.

**Comment by kutyel** [comment]
Looks like an easy fix, feel free to make a PR if you feel like doing it, if not I will do it this evening :wink:

**Comment by kutyel** [comment]
@lorenlew fixed, BTW support the project by giving it a ":star:" in GitHub! ;)
