### ISSUE TITLE
Undefined: Performance and logic

### ISSUE THREAD

**Issue by isc30** [kutyel/linq.ts#45]
Hi,

I noticed that you are using `undefined` as default value in `FirstOrDefault`, etc.

As seen [here](http://stackoverflow.com/questions/7283577/speed-of-comparing-to-null-vs-undefined-in-javascript), checking for `null` is way faster than `undefined` (and makes more sense from the design perspective).

What about me creating a PR to change all `undefined` to `null` when it makes sense?

**Comment by kutyel** [comment]
Of course! Feel free to do any PR you want! As long as it passes all the tests I will merge it without a problem 😉  (maybe you can even try to do some *benchmarking* agains your PR to test wether there is a real improvement as well). Thanks in advance!

**Comment by isc30** [comment]
Hi again! after thinking about this, I realized that the current status (using undefined) has more sense than null on cases like FirstOrDefault **BUT** we should mark return type as `T | undefined`.
I'll take care of that when I have time 😄

**Comment by isc30** [comment]
I will close this one and create a new issue for explicit undefined as return type

**Comment by isc30** [comment]
I finally did it from scratch, improved version can be found here:
https://github.com/isc30/linq-collections
