### ISSUE TITLE
Array -> List

### ISSUE THREAD

**Issue by isc30** [kutyel/linq.ts#46]
What about having something like:
```typescript
Array.prototype.toList = function<T>(): List<T> {
    return new List<T>(this);
}
```

**Comment by kutyel** [comment]
Sorry, this library's goal is to mimic the API from .NET LINQ, which does not have such method in it's `Array` definition. According to [this](http://stackoverflow.com/questions/2408367/net-converting-simple-arrays-to-list-generics) answer from StackOverflow, converting one `Array` to a `List` is as easy as passing it to its constructor:
```typescript
const strList = ["foo", "bar", "meh"];
const listOfStr = new List<string>(strList);
```

**Comment by isc30** [comment]
C# Array has [GetEnumerator()](https://msdn.microsoft.com/en-us/library/system.array.getenumerator(v=vs.110).aspx) that returns IEnumerable (the one you call List in your code).

Btw as IEnumerable has one extension method called [ToList()](https://msdn.microsoft.com/en-us/library/bb342261(v=vs.110).aspx), you can call `.ToList()` in a `Array<T>`.

Demo:
```
int[] a = {2, 3, 4, 5}; // Array<int>
var l = a.ToList(); // Array<int> -> IEnumerable<T> -> List<int>
l.Add(33);
Console.WriteLine(string.Join(",", l));
```
`>> 2,3,4,5,33`

**Comment by isc30** [comment]
So, are you doing this?

**Comment by kutyel** [comment]
I am opening it for discussion, but I personally don't like the idea of modifying prototypes as part of this library, anyone wanting this behaviour can easily do it themselves just as you mentioned.

**Comment by isc30** [comment]
Yep, I agree that changing native prototypes isn't a good idea. I open another issue to discuss other topic. You can close this one
