### ISSUE TITLE
MissInheritance of Enumerable

### ISSUE THREAD

**Issue by isc30** [kutyel/linq.ts#47]
In short words: everything must inherit from Enumerable

Currently on C#:

## `Enumerable<T>`:
    - Select
    - Where
    - First, Single
    - FirstOrDefault, SingleOrDefault
    - Basically all filter / select based methods

## `List<T>` extends `Enumerable<T>`
    - All inherited stuff
    - Add, Delete, DeleteWhere (or DeleteAll), ...
    - OrderBy, OrderByDesc

## `SortedList<T>` extends `List<T>`
    - Correctly implemented

## Etc ...

**Comment by kutyel** [comment]
You are right, the classes of the library are not exactly the same as in the .NET version, I always wanted to fix this, but I could not find an easy way to see the whole tree of methods, inheritance, etc.

**Comment by isc30** [comment]
I could help you, np.

Im working on a fully featured web framework and i would like this lib to be part of one module :D

**Comment by isc30** [comment]
ah que eres español tu también jajaj

**Comment by kutyel** [comment]
sí jajaja por tu nombre lo tenía claro pero al ver que ponías Spain / Poland he dudado jajaja 😜

**Comment by isc30** [comment]
Es que trabajo en polonia jaja

**Comment by isc30** [comment]
Hey again!
I decided to start a new **TsLinq** implementation from scratch.
This new implementation is iterator based, without copying memory all the time and O(n) for most operation chains.
If you want to help, we can make it really nice 😄
https://github.com/isc30/TsLinq

**Comment by kutyel** [comment]
Hi! I don't think creating your whole new library is a good approach to solving problems (*I was waiting for your PR to fix this issue*), I understand if you wanted to do it for learning purposes of your own though, but as it regards to this library, I already spend enough time and effort in making it the way it is, and don't feel like going through that process again to do something that I already implemented. By the way, there is already an existing version of LinQ for TypeScript with iterators, [here](https://github.com/ENikS/LINQ) 😄

**Comment by isc30** [comment]
Yep I've seen that one.
It has some problems: its ES6 and I want to run it on old mobile browsers (ES5). Also, does bad practices like changing prototype, casting things to `any`, not being 100% strongly typed and having memory "leaks") 😢
Don't worry, I will contribute with correct interfaces/design here

**Comment by kutyel** [comment]
Glad to hear, it seems that we are all trying to do the ***best*** implementation possible within our possibilities haha 😅
