### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by AcousticGuitar** [kutyel/linq.ts#53]
Typescript compiler options are:

```xml

  "compilerOptions": {
    "module": "amd",
    "moduleResolution": "node",
    "target": "es2016",
    "lib": [
      "es2016",
      "dom"
    ],
    "declarationDir": "node_modules/@types",
    "declaration": true,
    "outDir": "dist",
    "types": [
      "vss-web-extension-sdk",
      "c3",
      "d3",
      "jquery",
      "knockout"
    ]
  },
```
Upon Load the message _Uncaught ReferenceError: exports is not defined_ is seen in Chrome console pointing to line 372.

<img width="300" alt="exports" src="https://cloud.githubusercontent.com/assets/10676026/23616717/4aa1a2a4-0250-11e7-904b-9916a71d291b.PNG">

Attempts to install dependencies via NPM Update and or Install for this package doesn't work.  Please advise.

**Comment by kutyel** [comment]
Hi!

The library already provides an UMD compilation for browser, so there is no longer need to compile the code of the library itself. If you use it on Node.js, there is also a commonjs module. Try using the browser version and you should have the `exports` problem anymore!

I will reopen this issue if its an actual bug from the library 😉
