### ISSUE TITLE
After importing linqts error showed: linqts not found

### ISSUE THREAD

**Issue by AmirImam** [kutyel/linq.ts#55]
Hi, I am using a [linqts](https://github.com/kutyel/linq.ts) with angular 2 typescript (TypeScriptToolsVersion 1.8) project on vs 2015.
But when i do 
`import {List} from 'linqts';` and some code related to linq, it gives me an error on the browser 
**the server responded with a status of 404 (Not Found)**
and this is my tsconfit.json
```
{
 "compileOnSave": true,
 "compilerOptions": {
 "target": "es5",
 "module": "system",
 "moduleResolution": "node",
 "sourceMap": true,
 "emitDecoratorMetadata": true,
 "experimentalDecorators": true,
 "removeComments": false,
 "noImplicitAny": false
 },
 "exclude": [
 "node_modules"
 ] 
}
```
I don't know what i miss .. so I need some help with that .. thank you :)

**Comment by kutyel** [comment]
Are you using the lastest version of linqts? Please check #53 as well.

cc: @Zoxive @abbasmhd @Kurtz1993 @jamesrichford Is browser version still a problem? Having the UMD module should take care of that...

**Comment by AmirImam** [comment]
I am sorry, I don't understand you but I think you mean change "module":"system" to "module":"umd" .. if you mean that so I did it and nothing happened, if something else so please explain it :)

**Comment by AmirImam** [comment]
Some extra details 
 when I use "system" the error is "linqts not found"
 when I use "UMD" the error is "boot.js detected as register but didn't execute."
 when I use "commonjs" the error is "require is not defined"

**Comment by kutyel** [comment]
Please check the answers at #12, #16, #41 who had a the same issue and solved it. This is not a bug from the library. 😉
