### ISSUE TITLE
GroupBy and then select

### ISSUE THREAD

**Issue by Neir0** [kutyel/linq.ts#56]
Maybe I missed something but it looks like group by doesn't return collection and as result it is not possible to use Select with some aggregate operation.

What about returning IGrouping?

**Comment by kutyel** [comment]
You are right, right now the `GroupBy` function is not very usable due to the returning type, this could be very much improved and PR al welcome! 😉 👍

**Comment by marlon-tucker** [comment]
What's the status of this please?

GroupBy not having a typed return type is quite the hindrance IMO.

I have decent knowledge of both TS and LINQ so if you need a hand give me a shout.

**Comment by kutyel** [comment]
Hey @marlon-tucker! A PR it’s already open although the tests need some fixing and maybe the implementation as well 🙃. Please feel free to continue the work or provide your own solution, I’d be very willing to merge! 🙌🏼
