### ISSUE TITLE
Extension methods case question

### ISSUE THREAD

**Issue by stefan505** [kutyel/linq.ts#58]
I know that .NET types all use Pascal casing (e.g. FirstOrDefault), but would it not make more sense to have this lib follow the JS conventions of Camel casing (e.g. firstOrDefault)?

**Comment by kutyel** [comment]
Hi! Thanks for your question. It is true that the JavaScript community adopted the camel case convention, nevertheless, being this project in **TypeScript**, there isn't any specific convention already and I wanted to preserve the API from .NET exactly as it is (after all its a project focusing .NET Developers who want to give *JavaScript* development a try 😉 ).

**Comment by abinici** [comment]
Hi, I agree with @stefan505, it makes more sense that this project follows the conventions of JS, because TS is just JS with types. I think that pascal casing will just confuse new developers.
