### ISSUE TITLE
Any() doesn't have empty overload as .NET

### ISSUE THREAD

**Issue by Kurtz1993** [kutyel/linq.ts#59]
I found that when trying to use the .Any() method I'm getting an error because it's always expecting a predicate.
In .NET there's an overload that doesn't require a predicate and returns a boolean by checking if there are any elements (something like ```javascript this._elements.length > 0 ```

I will try to prepare a PR as well for this

**Comment by mzhukovs** [comment]
It appears this still causes an issue? If I use .Any() I get this console error:
Uncaught (in promise) TypeError: this.posts.Any is not a function
    at o.eval (VM652 ts-loader:43)
    at Generator.next (<anonymous>)
    at fulfilled (VM652 ts-loader:14)

.Any without parentheses appears to work.  @Kurtz1993  am I missing something? TIA.

**Comment by Kurtz1993** [comment]
Hi @mzhuvoks right noq I'm on vacaction. Returning on January 6th.

Can you give me a more detailed example of the issue so that I can work onit when I'm back?
Also, is the `this.posts` an instance of a List<>?

**Comment by Kurtz1993** [comment]
I will check the code as of today, because when I did the PR it was supposes to be used with parenthesis `.Any()`
