### ISSUE TITLE
.ToArray() confusing description? "Copies the elements of the List<T> to a new array."

### ISSUE THREAD

**Issue by zyarnold** [kutyel/linq.ts#65]
In your documentation you mentioned that List.ToArray() copies the elements of the List to a new array. But its actual function upon testing returns the same reference of the elements(which is good by the way because I would want to via linq and end up getting a new copy of the array of objects I want to modify) and not a copy of the new array.

**Comment by kutyel** [comment]
You are right, this is due to the fact that the documentation for each function is copied right away from .NET LINQ's spec, that's why it might differ from it's actual implementation. If you feel like updating the comment and providing a PR you will be very welcome 😉

**Comment by zyarnold** [comment]
Nah, Everything is good. I'm just curious if .ToArray() was really intended to copy a new array or return the same reference to those element list. I'm using linq.ts right now for a presentation project. And I want to be sure about the ToArray() function just in case it might be updated in the future to "copy new array" and might make breaking changes to my project :)

**Comment by kutyel** [comment]
Ok, I'm glad everything is fine, I wouldn't change something that importante without listing it as a breaking change anyway hehe 😉
