### ISSUE TITLE
Project has dependency to typescript?

### ISSUE THREAD

**Issue by ryanelian** [kutyel/linq.ts#73]
https://github.com/kutyel/linq.ts/blob/master/package.json

```json
  "dependencies": {
    "typescript": "^2.3.1"
  },
  "devDependencies": {
    "ava": "^0.20.0",
    "commitizen": "^2.8.6",
    "coveralls": "^2.11.14",
    "cz-conventional-changelog": "^2.0.0",
    "ghooks": "^2.0.0",
    "npm-run-all": "^4.0.0",
    "nyc": "^11.0.2",
    "rimraf": "^2.5.4",
    "semantic-release": "^6.3.2",
    "ts-loader": "^2.0.0",
    "ts-node": "^3.0.0",
    "tslint": "^5.0.0",
    "typedoc": "^0.7.0",
    "webpack": "^3.0.0"
  },
```

CMIIW, but shouldn't that be `devDependencies` instead? I don't see any TypeScript imports in https://github.com/kutyel/linq.ts/blob/master/linq.ts

I just don't feel comfortable downloading / having a 26 MB dependency inside my `node_modules` for a library that is only 50 KB in size...

**Comment by kutyel** [comment]
you are right, will remove it and release a new version without that depencency 😉

**Comment by kutyel** [comment]
Done in v1.8.3 👏
