### ISSUE TITLE
Help on GroupBy

### ISSUE THREAD

**Issue by Llarian** [kutyel/linq.ts#78]
Hi, how can I convert the result of the GroupBy to something enumerable?

**Comment by kutyel** [comment]
The quick answer is that right now, you can't (#56), but depending on what you want to do, you can use some *standard JavaScript functions* to work with the object that the `groupBy` function returns:
```ts
const pets = new List<Pet>([
    new Pet({ Age: 8, Name: 'Barley' }),
    new Pet({ Age: 4, Name: 'Boots' }),
    new Pet({ Age: 1, Name: 'Whiskers' }),
    new Pet({ Age: 4, Name: 'Daisy' })
])
const grouped = pets.GroupBy(pet => pet.Age, pet => pet.Name);
// > {
// >    '1': ['Whiskers'],
// >    '4': ['Boots', 'Daisy'],
// >    '8': ['Barley']
// > }
Object.keys(grouped);     // > ['1', '4', '8']
Object.values(grouped);  // > [['Whiskers'], ['Boots', 'Daisy'], ['Barley']]
Object.entries(grouped); // > [['1', ], ['4', ], ['8', ]]
```
Hope this helps!

**Comment by Llarian** [comment]
It did! You can use custom pipes to use this with ngFor: https://stackoverflow.com/a/37046743

**Comment by kutyel** [comment]
I am glad you fixed it! Since you are working with Angular 2... do you use webpack or SystemJS? Would you give a hand with #69? Thanks! 😄

**Comment by kutyel** [comment]
BTW! Support the library by giving it a ⭐️  in GitHub and sharing it with your colleages! 😉 👍
