### ISSUE TITLE
Error: InvalidOperationException: The source sequence is empty.

### ISSUE THREAD

**Issue by ikuriel** [kutyel/linq.ts#81]
Error: Uncaught (in promise): Error: InvalidOperationException: The source sequence is empty.
Error: InvalidOperationException: The source sequence is empty.

When an array is empty 
example:

```
let array: SelectItem[] = [];
const existingItem = new List<SelectItem>(array).
Where(x => x.value === compatMarca.value)
.First();
```

EDIT: i think the error is trhown after Where (because nothing is found) and First() of empty should returns "undefined", not Error.

**Comment by kutyel** [comment]
Hi, it is not a bug, is a controlled exception, according to [.NET's spec](https://msdn.microsoft.com/en-us/library/bb291976%28v=vs.100%29.aspx?f=255&MSPPError=-2147217396) for the method `First()` it *should* throw an exception if the sequence is empty.

**Comment by ikuriel** [comment]
.NET's spec sucks, thats all, ty.
