### ISSUE TITLE
SingleOrDefault doesnt accept predicate?

### ISSUE THREAD

**Issue by grofit** [kutyel/linq.ts#82]
In .net Linq you can do `myList.SingleOrDefault(x => x.someId == requiredId);` but I noticed in here there is no overload to support this like in .net.

https://msdn.microsoft.com/en-us/library/bb549274(v=vs.110).aspx

**Comment by kutyel** [comment]
True, should be done, and the same goes for `Single()`, Pull Requests are welcome! 🎉

**Comment by grofit** [comment]
PR raised for this.
