### ISSUE TITLE
Wrong signature of Select() or Distinct() methods

### ISSUE THREAD

**Issue by rxreyn3** [kutyel/linq.ts#94]
Hey guys and/or gals, just wondering if how I can avoid code like this while using ling.ts:

```js
var answers = new List(response.answers);
var vecs = answers.Select(answer => answer !== undefined ? answer.vecName : null).Distinct();
```

And instead simply write:
```js
answers.Select(answer => answer.vecName).Distinct();
```

Without the compiler warnings.

**Comment by isc30** [comment]
you can't, it has incorrect definitions for StrictNullCheck.
Try another libs like https://github.com/isc30/linq-collections
This one seems unmaintained

**Comment by rxreyn3** [comment]
Ok thanks!

-Ryan

**Comment by kutyel** [comment]
You can provide a PR and I'll be happy to merge 😄  This library is not unmaintained at all 😉

**Comment by isc30** [comment]
20 days without response and isn't unmaintained, ok

**Comment by kutyel** [comment]
I had an Issue with the email notifications but now is solved and the statistics of the library plus the *4k downloads/month* proves my point 🙃

**Comment by kutyel** [comment]
@rxreyn3 🎉 🎉 🎉
