### ISSUE TITLE
Custom providers or only collections

### ISSUE THREAD

**Issue by jeusdi** [kutyel/linq.ts#96]
Does it support the possibility to work with providers? Or it only works on collections? For example, could it be possible to create an odata provider?

**Comment by kutyel** [comment]
I am afraid this library only handles collections for the moment 🙃

**Comment by jeusdi** [comment]
Is there anyway to create a custom provider, I mean, is this library designed in a way to be able to extend it creating a custom provider?

**Comment by kutyel** [comment]
I don't think so, you would have to create something like your own wrapper of this library that connects to a particular DDBB (mongoDB, for example) and that changes every time because they are different between each other. Is that what you are looking for?

**Comment by jeusdi** [comment]
Sorry, please take a took on [here](http://www.c-sharpcorner.com/blogs/linq-providers1).

Linq is only an query dsl. So there're several providers that translate these queries to odata, collections, sql, excel, and so on... you are able to create your own linq provider using helping-libraries like [re-linq](https://github.com/re-motion/Relinq).

Do you know what I mean?

**Comment by kutyel** [comment]
I see, this library would be **LinQ to Objects**, no idea of how to implement a generic LINQ library that would allow you to implement your own LinQ to *Whatever* 😕
